name: neoargs
description: A fluent and idiomatic argument parser (usually for command-line apps) in Dart.
version: 0.0.0
homepage: https://github.com/neo-dart/neoargs

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  coverage: ^1.5.0
  neodart: ^0.1.1
  test: ^1.21.4
